name: "Slack Notify"
run-name: "${{ github.actor }} has created a ${{ github.ref }}"
on:
  create:
    branches:
      - "release/**"
  push:
    branches:
      - "release/**"
jobs:
  Slack-Notify:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
